export const REDUX_LIST_PRODUCT = 'listProduct';
export const LOAD_LIST_PRODUCT = `${REDUX_LIST_PRODUCT}/LOAD_LIST_PRODUCT`;
export const GET_PRODUCT_LIST = `${REDUX_LIST_PRODUCT}/GET_PRODUCT_LIST`;
export const SET_PRODUCT_LIST = `${REDUX_LIST_PRODUCT}/SET_PRODUCT_LIST`;
